print("\tBIO DATA\n")
print("Name: Im Dilipkumar R")
print("Date of Birth: 15 August 2002")
print("Gender: male")
print("MY FAMILY MEMBERS")
print("Father: Rajasekar M")
print("Mother: Jayachithra R")
print("Sister: Padmapriya R")
print("Address: koolapandi,Madurai ")
print("Phone: 9384977792")
print("Email: 833dilipkumar@gmail.com")
print("Undergraduation: Bachelor of Computer Science")
print("Postgraduation: Masters in Computer Application")
print("Skills: Python,java, HTML, CSS, Javascript, SQL")
print("Hobbies: Carrom,gaming")
print("Language Known: English, Tamil")
print("Nationality: Indian")
print(" completed Undergraduation in thiagaraja arts and science college")
print(" completed Post Graduation in Madurai kamaraja university")
