print("SSLC MARKS")
print("Tamil: 80")
print("English: 69")
print("Mathematics: 61")
print("Science: 86")
print("Social Science: 79")
print("SSLC MARKS percentage: 75%")

print("HSC MARKS")
print("Tamil: 59")
print("English: 63")
print("Mathematics: 53")
print("Computer Science: 84")
print("Physics: 53")
print("Chemistry: 49")

print("HSC MARKS percentage: 59%")      
print("Undergraduation CGPA: 86%")
print("Post Graduation CGPA: 72%")
